- name: Todo project
  hosts: localhost
  become: yes
  tasks:
    - name: install inginx
      apt:
        name: nginx
        update_cache: yes
    - name: start nginx
      systemd:
        state: started
        name: nginx
        enabled: yes
    - name: download foo.conf
      get_url:
        url: http://http://34.201.8.112:8081/repository/frontend/frontend-main.zip
        dest: /tmp/frontend-main.zip
        username: admin
        password: admin

    - name: install npm
      apt:
        name: npm
        update_cache: yes
