- name: Todo project
  hosts: all
  become: yes
  tasks:
    - name: install inginx
      apt:
        name: nginx
        update_cache: yes
    - name: start nginx
      systemd:
        state: started
        name: nginx
        enabled: yes
