- name: Todo project
  hosts: localhost
  become: yes
  tasks:
    - name: install inginx
      apt:
        name: nginx
        update_cache: yes
    - name: start nginx
      systemd:
        state: started
        name: nginx
        enabled: yes
    - name: download artifacts
      get_url:
        url: http://34.232.48.79:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip
        username: admin
        password: admin

    - name: install npm
      apt:
        name: npm
        update_cache: yes
