 - name: Todo project
   hosts: localhost
   become: yes
   tasks:

    - name: install inginx
      apt:
        name: nginx
        update_cache: yes

    - name: download foo.conf
      get_url:
        url:  http://3.80.109.246:8081/repository/frontend/frontend-main.zip
        dest: /tmp/frontend-main.zip
        username: admin
        password: admin

    - name: ansible create directory example
      file:
         path: /var/www/html/todo/frontend
         state: directory

    - unarchive:
        src: /tmp/frontend-main.zip
        dest: /var/www/html/todo/frontend
        remote_src: True

    - name: install npm
      apt:
        name: npm
        update_cache: yes

    - name: install nodejs
      apt:
        name: nodejs
        update_cache: yes

    - name: Replace after the expression till the end of the file (requires Ansible >= 2.4)
      replace:
        path: /etc/nginx/sites-available/default
        after: /var/www/html
        regexp: '^(.+)$'
        replace: todo/frontend/dist;

    - name: Change the working directory to somedir and start npm
      shell:  npm run build && npm start
      args:
        chdir: /var/www/html/todo/frontend

   # - name: Execute a command using the shell module
    #    become: true
     #   become_user: root
      #  shell: npm start

    - name: Copy file conf file
      ansible.builtin.copy:
        src: /var/www/html/todo/todo.conf
        dest: /etc/systemd/system/

    - name: Make sure a service is running
      systemd:
        state: started
        name: todo
    - name: start nginx
      service:
        name: nginx
        state: started


     # - name: Start service foo, based on running process /usr/bin/foo
     # service:
     #   name: npm
     #   pattern: /var/www/html/todo
     #   state: started

