- name: Todo project
  hosts: localhost
  become: yes
  tasks:

    - name: Update all Ubuntu packages
      apt:
        upgrade: "dist"
      when: ansible_distribution == 'Ubuntu'

    - name: Install required Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - openjdk-8-jdk

     #- name: install java
     # apt:
      #  name: openjdk-8-jdk
       # state: present
       # enabled: yes

    - name: download foo.conf
      get_url:
        url: http://54.91.69.17:8081/repository/users/users-main.zip
        dest: /tmp/users-main.zip
        username: admin
        password: admin

    - unarchive:
        src: /tmp/users-main.zip
        dest: /home/ubuntu
        remote_src: True

    - name: install the latest version of Apache Maven
      apt:
        name: maven
        state: latest

    #- name: build packages
     # shell: mvn compile package
      #become: yes
      #args:
       #   chdir: /home/ubuntu

    - name: Running mvn clean
      shell: "mvn clean install"
      register: mvn_result
      args:
        chdir: /home/ubuntu

    - name: Ansible copy file to remote server
      copy:
        src: /home/ubuntu/systemd.service
        dest: /etc/systemd/system/users.service


