- name: Todo project
  hosts: localhost
  become: yes
  tasks:

    - name: install golang
      apt:
        name: golang-go
        state: present
        update_cache: yes

    - name: download foo.conf
      get_url:
        url: http://54.92.223.206:8081/repository/login/login-main.zip
        dest: /tmp/login-main.zip
        username: admin
        password: admin

    - name: ansible create directory example
      file:
        path: /home/ubuntu/login
        state: directory

    - unarchive:
        src: /tmp/login-main.zip
        dest: /home/ubuntu/login

      #- name: build the files of login
      # shell: export GOPATH =/go
      # become: yes
      # args:
      #  chdir: /home/ubuntu/login

    - name: Ansible copy file to remote server
      copy:
        src: /home/ubuntu/login/systemd.service
        dest: /etc/systemd/system/login.service

